### ISSUE TITLE
Special Morphisms with derived objects

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#86]
Related to #63 and #85. In my `FreeChemistry` syntax, we have `degraded(X)::Ob` for any `X::Ob`. How do you tell `@parse_wiring_diagram` how to express `mmerge{degraded(X)}`?

I thought at lease one of these would work:

```julia
d = @parse_wiring_diagram Cannibalism (a::A, b::B, c::C) begin
    ac = bind{A,C}(a,c)
    a, c_deg1 = degrade{A,C}(ac)
    bc = bind{B,C}(b,c)
    b, c_deg2 = degrade{B,C}(bc)
    c_deg  = mmerge{degraded{C}}(c_deg1,c_deg2)
    return c_deg
end

d = @parse_wiring_diagram Cannibalism (a::A, b::B, c::C) begin
    ac = bind{A,C}(a,c)
    a, c_deg1 = degrade{A,C}(ac)
    bc = bind{B,C}(b,c)
    b, c_deg2 = degrade{B,C}(bc)
    c_deg  = mmerge{degraded(C)}(c_deg1,c_deg2)
    return c_deg
end
```

**Comment by epatters** [comment]
Hmm, I think the first one should work. This is probably a bug. Can you post the stack trace for the first snippet?

**Comment by jpfairbanks** [comment]
```
AssertionError: all((has_generator(pres, name) for name = inputs))

Stacktrace:
 [1] parse_wiring_diagram(::Presentation{Symbol}, ::Expr, ::Expr) at /Users/jfairbanks6/.julia/packages/Catlab/BhYS1/src/programs/JuliaPrograms.jl:266
 [2] top-level scope at In[183]:1
```

**Comment by epatters** [comment]
Actually, I'm not sure whether this is a bug. I added some further tests, which are passing.

The assertion error suggests that one of the types in the function signature (`A`, `B`, or `C`) is not in the presentation `Cannibalism`. Can you show the code for `Cannabilism`?

**Comment by jpfairbanks** [comment]
I think this is a MWE.

```julia
using Pkg
Pkg.activate("..")
using Catlab

using Catlab.Doctrines

using Catlab.Graphics
using Catlab.Programs

using Catlab.WiringDiagrams

import Catlab.Doctrines: otimes, ⊗, dom, codom, compose
import Catlab: dom, codom
@signature BiproductCategory(Ob,Hom) => Chemistry(Ob,Hom) begin
    complex(X::Ob,Y::Ob)::Ob
    bind(X::Ob, Y::Ob)::Hom(otimes(X,Y),complex(X,Y))
    degraded(X::Ob)::Ob
    degrade(X::Ob,Y::Ob)::Hom(complex(X,Y), otimes(X, degraded(Y)))
    # cleaving is not a fundamental operation so we normalize it out of the syntax
    cleave(X::Ob, Y::Ob)::Hom(otimes(X,Y),otimes(X,degraded(Y)))
end

@syntax FreeChemistry(ObExpr,HomExpr) Chemistry begin
  otimes(A::Ob, B::Ob) = associate_unit(new(A,B), munit)
  otimes(f::Hom, g::Hom) = associate(new(f,g))
  compose(f::Hom, g::Hom) = associate(new(f,g; strict=true))

  pair(f::Hom, g::Hom) = compose(mcopy(dom(f)), otimes(f,g))
  copair(f::Hom, g::Hom) = compose(otimes(f,g), mmerge(codom(f)))
  proj1(A::Ob, B::Ob) = otimes(id(A), delete(B))
  proj2(A::Ob, B::Ob) = otimes(delete(A), id(B))
  incl1(A::Ob, B::Ob) = otimes(id(A), create(B))
  incl2(A::Ob, B::Ob) = otimes(create(A), id(B))
    
  # cleaving is not a fundamental operation so we normalize it out of the syntax
  cleave(A::Ob, B::Ob) = bind(A,B)⋅degrade(A,B)
end

@present P(FreeChemistry) begin
    ## list of objects
    A::Ob
    B::Ob
    C::Ob
end

degraded(p::Ports{Chemistry.Hom}) = Ports{Chemistry.Hom}(degraded.(p.ports))
complex(p::Ports{Chemistry.Hom}, q::Ports{Chemistry.Hom}) = begin
    z = collect(zip(p.ports, q.ports))
    Ports{Chemistry.Hom}([complex(a,b) for (a,b) in z])
end
degrade(p::Ports{Main.Chemistry.Hom}, q::Ports{Main.Chemistry.Hom}) = begin
    singleton_diagram(Box(:degrade, complex(p,q), degraded(q)))
end

bind(p::Ports{Main.Chemistry.Hom}, q::Ports{Main.Chemistry.Hom}) = begin
    a = length(p.ports) > 1 ? otimes(p.ports) : p.ports[1]
    b = length(q.ports) > 1 ? otimes(q.ports) : q.ports[1]
    c = complex(a,b)
    return singleton_diagram(Box(:bind, Ports([p.ports..., q.ports...]), Ports([c])))
    #to_wiring_diagram(Hom(:bind, otimes(p.ports..., q.ports...), c), keep_exprs=true)
end


d = @parse_wiring_diagram P (a::A, b::B) begin
    ab = bind{A,B}(a,b)
end
```
Stacktrace:
```
MethodError: no method matching complex(::Symbol, ::Symbol)

Stacktrace:
 [1] bind(::Ports{Main.Chemistry.Hom,Symbol}, ::Ports{Main.Chemistry.Hom,Symbol}) at ./In[4]:58
 [2] invoke_term(::Module, ::Tuple{UnionAll,UnionAll}, ::Symbol, ::Ports{Main.Chemistry.Hom,Symbol}, ::Vararg{Ports{Main.Chemistry.Hom,Symbol},N} where N) at /Users/jfairbanks6/.julia/dev/Catlab/src/core/GAT.jl:581
 [3] #functor#30(::Dict{Any,Any}, ::Dict{Symbol,Function}, ::typeof(functor), ::Tuple{UnionAll,UnionAll}, ::Main.FreeChemistry.Hom{:bind}) at /Users/jfairbanks6/.julia/dev/Catlab/src/core/Syntax.jl:399
 [4] (::getfield(Catlab.Syntax, Symbol("#kw##functor")))(::NamedTuple{(:terms,),Tuple{Dict{Symbol,Function}}}, ::typeof(functor), ::Tuple{UnionAll,UnionAll}, ::Main.FreeChemistry.Hom{:bind}) at ./none:0
 [5] #to_wiring_diagram#2(::Bool, ::typeof(to_wiring_diagram), ::Type, ::Main.FreeChemistry.Hom{:bind}) at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Expressions.jl:35
 [6] to_wiring_diagram at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Expressions.jl:35 [inlined]
 [7] #to_wiring_diagram#1 at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Expressions.jl:32 [inlined]
 [8] to_wiring_diagram at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Expressions.jl:31 [inlined]
 [9] record_call!(::WiringDiagram{Any}, ::Main.FreeChemistry.Hom{:bind}, ::Port, ::Vararg{Port,N} where N) at /Users/jfairbanks6/.julia/dev/Catlab/src/programs/JuliaPrograms.jl:338
 [10] (::getfield(Catlab.Programs.JuliaPrograms, Symbol("##21#29")){Main.FreeChemistry.Hom{:bind},WiringDiagram{Any}})(::Port, ::Vararg{Port,N} where N) at /Users/jfairbanks6/.julia/dev/Catlab/src/programs/JuliaPrograms.jl:270
 [11] ##54#55(::Main.FreeChemistry.Ob{:generator}, ::Main.FreeChemistry.Ob{:generator}, ::getfield(Catlab.Programs.JuliaPrograms, Symbol("##34#36")){Module,Symbol}, ::getfield(Catlab.Programs.JuliaPrograms, Symbol("##54#56")), ::getfield(Catlab.Programs.JuliaPrograms, Symbol("##20#28")){WiringDiagram{Any}}, ::Port, ::Port) at ./In[4]:65
 [12] ##54#56 at ./none:0 [inlined]
 [13] (::getfield(Base, Symbol("#inner#2")){Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:A, :B, :bind),Tuple{Main.FreeChemistry.Ob{:generator},Main.FreeChemistry.Ob{:generator},getfield(Catlab.Programs.JuliaPrograms, Symbol("##34#36")){Module,Symbol}}}},getfield(Catlab.Programs.JuliaPrograms, Symbol("##54#56")),Tuple{getfield(Catlab.Programs.JuliaPrograms, Symbol("##20#28")){WiringDiagram{Any}},Port,Port}})() at ./essentials.jl:793
 [14] #invokelatest#1(::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:A, :B, :bind),Tuple{Main.FreeChemistry.Ob{:generator},Main.FreeChemistry.Ob{:generator},getfield(Catlab.Programs.JuliaPrograms, Symbol("##34#36")){Module,Symbol}}}}, ::typeof(Base.invokelatest), ::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:794
 [15] (::getfield(Base, Symbol("#kw##invokelatest")))(::NamedTuple{(:A, :B, :bind),Tuple{Main.FreeChemistry.Ob{:generator},Main.FreeChemistry.Ob{:generator},getfield(Catlab.Programs.JuliaPrograms, Symbol("##34#36")){Module,Symbol}}}, ::typeof(Base.invokelatest), ::Function, ::Function, ::Vararg{Any,N} where N) at ./none:0
 [16] parse_wiring_diagram(::Presentation{Symbol}, ::Expr, ::Expr) at /Users/jfairbanks6/.julia/dev/Catlab/src/programs/JuliaPrograms.jl:271
 [17] top-level scope at In[4]:62
```

I think the problem might be that the `@parse_wiring_diagram` part doesn't use `keep_exprs` option.

**Comment by epatters** [comment]
With the above commit, your code will work if you add:

```julia
import Catlab.WiringDiagrams: to_wiring_diagram

to_wiring_diagram(expr::FreeChemistry.Hom) = begin
  to_wiring_diagram(expr, identity, identity)
end
```

The `keep_exprs` option is now gone. See the commit for details.

**Comment by epatters** [comment]
FYI, there are some lingering issues here that I'm working on cleaning up.

**Comment by epatters** [comment]
OK, this should work now! Let me know if there are further problems.

**Comment by jpfairbanks** [comment]
I finally got a chance to work on this. Checking now

**Comment by jpfairbanks** [comment]
When I do 

```julia
to_wiring_diagram(bind(A,B))
```

I get the stacktrace:

```
MethodError: no method matching to_wiring_diagram(::Main.FreeChemistry.Hom{:bind}, ::typeof(identity), ::typeof(identity))
Closest candidates are:
  to_wiring_diagram(::Union{Main.FreeChemistry.Hom, Main.FreeChemistry.Ob}) at In[2]:53

Stacktrace:
 [1] to_wiring_diagram(::Main.FreeChemistry.Hom{:bind}) at ./In[2]:54
 [2] top-level scope at In[5]:1
```
which doesn't make sense.

**Comment by jpfairbanks** [comment]
When I call this function directly,
```julia
to_wiring_diagram(bind(A,B), identity, identity)
```
I still get:
```
MethodError: no method matching to_wiring_diagram(::Main.FreeChemistry.Hom{:bind}, ::typeof(identity), ::typeof(identity))
Closest candidates are:
  to_wiring_diagram(::Union{Main.FreeChemistry.Hom, Main.FreeChemistry.Ob}) at In[2]:53

Stacktrace:
 [1] top-level scope at In[4]:1
```

I feel like this might be a version problem, I pulled master into my local development branch.

**Comment by epatters** [comment]
Are you sure that you are on master branch and that you have a line that says `import Catlab.WiringDiagrams: to_wiring_diagram`?

**Comment by jpfairbanks** [comment]
missing import....duh

**Comment by jpfairbanks** [comment]
Success!

![image](https://user-images.githubusercontent.com/2753998/73402149-38a26480-42b2-11ea-9128-a40cf55f5941.png)

**Comment by jpfairbanks** [comment]
Gotta rollback that 🎉 . I think we broke mmerge though. 

```julia
to_wiring_diagram(mmerge(A))
```

```
MethodError: no method matching mmerge(::Ports{Main.Chemistry.Hom,Main.FreeChemistry.Ob{:generator}})
Closest candidates are:
  mmerge(!Matched::Ports{Main.Chemistry.Hom,Main.FreeChemistry.Ob{:degraded}}) at In[129]:2
  mmerge(!Matched::Main.Chemistry.Ob) at none:0
  mmerge(!Matched::Main.FreeChemistry.Ob) at none:0
  ...

Stacktrace:
 [1] invoke_term(::Module, ::Tuple{UnionAll,UnionAll}, ::Symbol, ::Ports{Main.Chemistry.Hom,Main.FreeChemistry.Ob{:generator}}, ::Vararg{Ports{Main.Chemistry.Hom,Main.FreeChemistry.Ob{:generator}},N} where N) at /Users/jfairbanks6/.julia/dev/Catlab/src/core/GAT.jl:581
 [2] #functor#30(::Dict{Any,Any}, ::Dict{Symbol,Function}, ::typeof(functor), ::Tuple{UnionAll,UnionAll}, ::Main.FreeChemistry.Hom{:mmerge}) at /Users/jfairbanks6/.julia/dev/Catlab/src/core/Syntax.jl:399
 [3] (::getfield(Catlab.Syntax, Symbol("#kw##functor")))(::NamedTuple{(:terms,),Tuple{Dict{Symbol,Function}}}, ::typeof(functor), ::Tuple{UnionAll,UnionAll}, ::Main.FreeChemistry.Hom{:mmerge}) at ./none:0
 [4] to_wiring_diagram(::Type, ::Main.FreeChemistry.Hom{:mmerge}, ::typeof(identity), ::typeof(identity)) at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Expressions.jl:38
 [5] to_wiring_diagram at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Expressions.jl:32 [inlined]
 [6] to_wiring_diagram(::Main.FreeChemistry.Hom{:mmerge}) at ./In[18]:68
 [7] top-level scope at In[131]:1
```

**Comment by jpfairbanks** [comment]
So you do have to import everything, which we should fix or enumerate: `import Catlab.Doctrines: otimes, ⊗, dom, codom, compose, mmerge, create, delete, mcopy`.

But then I still get this error message:

```
MethodError: no method matching mmerge(::Ports{Main.Chemistry.Hom,Main.FreeChemistry.Ob{:generator}}, ::Int64)
Closest candidates are:
  mmerge(!Matched::NLayer, ::Int64) at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Layers.jl:209
  mmerge(!Matched::Catlab.Programs.ExpressionTrees.NFormula, ::Int64) at /Users/jfairbanks6/.julia/dev/Catlab/src/programs/ExpressionTrees.jl:158
  mmerge(!Matched::Ports{Any,Value} where Value, ::Int64) at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Algebraic.jl:209
  ...

Stacktrace:
 [1] mmerge(::Ports{Main.Chemistry.Hom,Main.FreeChemistry.Ob{:generator}}) at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Algebraic.jl:214
 [2] invoke_term(::Module, ::Tuple{UnionAll,UnionAll}, ::Symbol, ::Ports{Main.Chemistry.Hom,Main.FreeChemistry.Ob{:generator}}, ::Vararg{Ports{Main.Chemistry.Hom,Main.FreeChemistry.Ob{:generator}},N} where N) at /Users/jfairbanks6/.julia/dev/Catlab/src/core/GAT.jl:581
 [3] #functor#30(::Dict{Any,Any}, ::Dict{Symbol,Function}, ::typeof(functor), ::Tuple{UnionAll,UnionAll}, ::Main.FreeChemistry.Hom{:mmerge}) at /Users/jfairbanks6/.julia/dev/Catlab/src/core/Syntax.jl:399
 [4] (::getfield(Catlab.Syntax, Symbol("#kw##functor")))(::NamedTuple{(:terms,),Tuple{Dict{Symbol,Function}}}, ::typeof(functor), ::Tuple{UnionAll,UnionAll}, ::Main.FreeChemistry.Hom{:mmerge}) at ./none:0
 [5] to_wiring_diagram(::Type, ::Main.FreeChemistry.Hom{:mmerge}, ::typeof(identity), ::typeof(identity)) at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Expressions.jl:38
 [6] to_wiring_diagram at /Users/jfairbanks6/.julia/dev/Catlab/src/wiring_diagrams/Expressions.jl:32 [inlined]
 [7] to_wiring_diagram(::Main.FreeChemistry.Hom{:mmerge}) at ./In[1]:68
 [8] top-level scope at In[10]:1
```

It looks like the ports are being passed to mmerge individually instead of as an array.

**Comment by epatters** [comment]
So, what happened here is that my fixing a bug earlier revealed another problem. Previously, `@parse_wiring_diagram` returned an untyped wiring diagram (`WiringDiagram{Any}`), but that is clearly wrong because the presented category belongs to some doctrine. Now it correctly returns a typed wiring diagram (in this case `WiringDiagram{Chemistry.Hom}`).

In typed wiring diagrams, `mcopy` and `mmerge` are, by default, not implemented. This makes sense, because e.g. in a cartesian monoidal category you cannot `mmerge`. So you need to define these methods for `WiringDiagram{Chemistry.Hom}`. The commits above are intended to make this more convenient.

If you want the implicit representation, write:

```julia
mcopy(A::Ports{Chemistry.Hom}, n::Int) = implicit_mcopy(A, n)
mmerge(A::Ports{Chemistry.Hom}, n::Int) = implicit_mmerge(A, n)
```

Calling `to_wiring_diagram(compose(mcopy(A), mmerge(A)))` then gives

```
[ 1 => {inputs},
  2 => {outputs},
   ],
[ Wire((1,1) => (2,1)),
  Wire((1,1) => (2,1)) ])
```

If you want the explicit representation, using junction nodes, write:

```julia
mcopy(A::Ports{Chemistry.Hom}, n::Int) = junctioned_mcopy(A, n)
mmerge(A::Ports{Chemistry.Hom}, n::Int) = junctioned_mmerge(A, n)
```

Calling the same code then gives

```
WiringDiagram{Main.Chemistry.Hom}([A], [A],
[ 1 => {inputs},
  2 => {outputs},
  3 => Junction{nothing,Ob{:generator}}(A, Main.FreeChemistry.Ob{:generator}[A], Main.FreeChemistry.Ob{:generator}[A, A]),
  4 => Junction{nothing,Ob{:generator}}(A, Main.FreeChemistry.Ob{:generator}[A, A], Main.FreeChemistry.Ob{:generator}[A]) ],
[ Wire((1,1) => (3,1)),
  Wire((3,1) => (4,1)),
  Wire((3,2) => (4,2)),
  Wire((4,1) => (2,1)) ])
```

**Comment by jpfairbanks** [comment]
Success! 🎉 🚢 🇮🇹 
![image](https://user-images.githubusercontent.com/2753998/73452558-be182a00-432f-11ea-84d7-d46daee29580.png)

**Comment by epatters** [comment]
Good! I will restore the 🎉 and hazard to close this issue again.
